### ISSUE TITLE
Environment files

### ISSUE THREAD

**Issue by AlbertDeFusco** [sophiamyang/sophiamyang.github.io#1]
One small suggestion. To help make the `environment.yml` files more applicable across platforms you can run

```
conda env export --from-history -n <env-name>
```

**Comment by sophiamyang** [comment]
Good to know! Thanks @AlbertDeFusco 😊

**Comment by sophiamyang** [comment]
Weird after adding --from-history, pip packages won't show up @AlbertDeFusco

**Comment by AlbertDeFusco** [comment]
Yeah, I've meaning to setup a PR to Conda for that
