### ISSUE TITLE
@bokehJS

### ISSUE THREAD

**Issue by SerRichard** [sophiamyang/sophiamyang.github.io#2]
Using the given build environment I can't seem to import the modules.

Import throws 
´´´
Javascript error adding output!
Error: Cannot find module '@bokehjs/styles/buttons'
See your browser Javascript console for more details.
´´´

Have you experienced this your end?

I have narrowed it down to:
import hvplot.pandas

Additionally, I am unable to display any PeriodicDataFrame, even in a simpler script. I feel as though that may be related to the JS error being thrown.

Any ideas to solve this would be appreciated, if you need any other info just let me know.

**Comment by sophiamyang** [comment]
I'm not sure and I haven't seen that error message before. Sometimes updating packages (e.g., conda update notebook hvplot ...) helps. Were you able to see the plots and dashboard though?

**Comment by SerRichard** [comment]
Hi!

 So I did have some success installing the packages locally via pip, I think something my end fussed with the build.
 Via pip and then in a jupyter server I've managed to get it working. Cool demo!

Consider it closed :)

**Comment by sophiamyang** [comment]
Thanks! Yeah, packaging issues can be annoying sometimes. I am glad you made it work! :)
