### ISSUE TITLE
How to solve this error ?

### ISSUE THREAD

**Issue by kirillportfolio** [sophiamyang/sophiamyang.github.io#3]
(base) C:\Users\Admin\Desktop\wheather>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - notebook==6.2.0=py38hecd8cb5_0
  - pandas==1.2.1=py38hb2f4e1b_0
  - python==3.8.5=h26836e1_1
  - numpy==1.19.2=py38h456fd55_0

**Comment by sophiamyang** [comment]
Please try `conda install datashader holoviews hvplot notebook numpy pandas panel param requests streamz` in your environment directly.
